---
title: "TFFF Layered Map"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(here)
library(tigris)
library(janitor)
library(tmap)
library(sf)
library(leaflet)
library(leaflet.extras)


tfff_grants <- read_sf(here("data", "tfff_grants.shp")) %>% 
     mutate(rown = row_number()) %>% 
     mutate(name = str_glue("Grant Number {rown}"))


tfff_grants_by_county <- read_sf(here("data", "tfff_grants_by_county.shp"))

# Colors

tfff_dark_green <- "#265142"
tfff_light_green <- "#B5CC8E"
tfff_orange <- "#e65100"
tfff_yellow <- "#FBC02D"
tfff_blue <- "#283593"
tfff_red <- "#B71C1C"
tfff_brown <- "#51261C"
tfff_dark_gray <- "#545454"
tfff_medium_gray <- "#a8a8a8"
tfff_light_gray <- "#eeeeee"

tfff_depts_pal <- c("tfff_yellow",
                         "tfff_red",
                         "tfff_orange",
                         "tfff_blue")

```

# Regular Map

```{r}

tmap_mode("view")


tm_basemap(leaflet::providers$Wikimedia) +
tm_shape(tfff_grants_by_county,
         "County Totals",
         legend.position = NA) +
     tm_polygons(col = "total",
                 title = "County Totals",
                 legend.show = F,
                 alpha = 0.6,
                 palette = "Oranges") +
     tm_shape(tfff_grants,
              "Individual Grants") +
     tm_dots(size = "size",
             title = "",
             alpha = 0.75,
             palette = "Set1",
             col = "department",
             n = 4) 

# tmaptools::palette_explorer()


```

# Heatmap

```{r}
leaflet(tfff_grants) %>%
     addProviderTiles(providers$CartoDB.Positron) %>%
     addHeatmap(blur = 32,
                max = 0.0001)
```



